steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set app/project 'ahp-entropy' \
        && gcloud config set app/cloud_build_timeout 3600 \
        && gcloud app deploy -q --no-promote --stop-previous-version --verbosity=debug -v=$BUILD_ID \
        --project='ahp-entropy'

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
